### ISSUE TITLE
Allow the BME280 device to also be used on I2C

### ISSUE THREAD

**Issue by timcnicholls** [stfc-aeg/odin-devices#4]
The current BME280 module supports SPI, but the physical device supports both SPI and I2C. 

The MERCURY test board has a BME280 device hooked up to I2C so we should investigate how to make the underlying device select the bus type.

Tagging @TeraMike and @josephnobes-stfc as assignees for reference.

**Comment by josephnobes-stfc** [comment]
How complex would it be to wrap a C driver as an ODIN device? Would it be possible to make user of [Bosch's API](https://github.com/BoschSensortec/BME280_driver)?

I suppose it might make any testing using something like pytest quite a lot harder. Also not sure about the license.

**Comment by timcnicholls** [comment]
It's probably overkill TBH. We can decouple the `BME280` class from inheriting from `SPIDevice` and have it instantiate an `I2CDevice` or `SPIDevice` member, then route the low level access `_readXXX` and `_writeXXX` to the appropriate device calls.

**Comment by josephnobes-stfc** [comment]
Yep OK, sounds like a plan!
